name: Publish Docker Image
on:
  push:
    branches: 
      - 'main'
  release:
    types:
      - published
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: marcos187/docker-ss-xray
          tags: |
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      -
        name: login to GHCR
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: build image
        uses: docker/build-push-action@v3
        with:
          tags:  ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
      -
        name: push build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
